version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./www/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - internal
    volumes:
      - ./www/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
  db:
    image: mysql:5.7
    restart: always
    networks:
      - internal
    environment:
      MYSQL_DATABASE: 'test_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'devuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'devpass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'devpass'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql_data:/var/lib/mysql
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
networks:
  internal:
    driver: bridge